accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup" ),

]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path("", include("tools.urls", namespace="tools")),
]

tools/urls.py
from django.urls import path

from . import views

app_name = "tools"

urlpatterns = [
path("", views.StartPage.as_view(), name="base"),
path("my_tools/", views.MyToolsView.as_view(), name="mytools"),
path("new_tool/", views.NewToolView.as_view(), name="newtool"),
path("delete/<int:pk>", views.DeleteToolView.as_view(), name="deletetool"),
path("update_tool/<int:pk>", views.UpdateToolView.as_view(), name="update_tool"),
path("neighbors/",views.NeighborsView.as_view(), name="neighbors"),
path("borrower_feed/", views.BorrowerView.as_view(), name="borrower_feed"),
path("users_tool/<int:pk>", views.UsersToolView.as_view(), name="users_tool")
]

accounts/models.py
from django.db import models

# Create your models here.

tools/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your models here.

class Tool(models.Model):
    HAND_TOOL = "HAND TOOL"
    GARDEN_TOOL = "GARDEN TOOL"
    POWER_TOOL = "POWER TOOL"


    Type_Choices = [
        (HAND_TOOL,"Hand Tool"),
        (GARDEN_TOOL, "Garden Tool"),
        (POWER_TOOL, "Power Tool"),
    ]

    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255, choices=Type_Choices, default=HAND_TOOL)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=False)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login

# Create your views here.


class SignupView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("tools:mytools")
    template_name = "signup.html"

tools/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Tool
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model

User = get_user_model()


class StartPage(generic.TemplateView):
    template_name = "tools/base.html"


class MyToolsView(LoginRequiredMixin, generic.ListView):
    template_name = "tools/my_tools.html"
    model = Tool
    context_object_name = "tool_list"
    def get_queryset(self):
        return Tool.objects.filter(owner=self.request.user)


class NewToolView(LoginRequiredMixin, generic.CreateView):
    model = Tool
    fields = ["name","type","is_available",]
    template_name = "tools/new_tool.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy("tools:mytools")


class DeleteToolView(LoginRequiredMixin, generic.DeleteView):
    model = Tool

    def get_object(self, queryset=None):
        tool = super(DeleteToolView, self).get_object()
        if not tool.owner == self.request.user:
            raise Http404
        return tool
    success_url = reverse_lazy("tools:mytools")


class UpdateToolView(LoginRequiredMixin, generic.UpdateView):
    model = Tool
    fields = ["name", "type","is_available",]
    template_name = 'tools/my_tool_update_form.html'

    success_url = reverse_lazy("tools:mytools")




class NeighborsView(generic.ListView):
    model = User
    template_name = "tools/neighbors.html"
    context_object_name = "neighbors_list"
    def get_queryset(self):
        return User.objects.exclude(username="admin")

class BorrowerView(LoginRequiredMixin,generic.ListView):
    model = Tool
    template_name = "tools/borrower.html"
    context_object_name = "borrower_list"

    def get_queryset(self):
        return Tool.objects.all()


class UsersToolView(LoginRequiredMixin,generic.ListView):
    model = Tool
    template_name = "tools/users_tool.html"
    context_object_name = "users_tool_list"

    def get_queryset(self):
        return Tool.objects.filter(owner = self.kwargs["pk"])


# class Borrow_tool(LoginRequiredMixin , generic.UpdateView):
#     model = Tool
#     template_name = "tools/users_tool.html"
#     def get_queryset(self):
#         retTool.objects.filter(self= self.request.id).update(is_available = False)

accounts/templates/signup.html
{% extends "./tools/base.html" %}

{% block content %}
<section>
    <h2>Sign up </h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>Sign Up</button>

    </form>
</section>
{% endblock %}

tools/templates/tools/base.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static 'tools/base.css' %}" >
        <link href="https://fonts.googleapis.com/css?family=Modak&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body class="container">
        {% include "tools/header.html" %}
        {% include "tools/getstarted.html" %}
        {% block content %}
        {% endblock %}
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

tools/templates/tools/borrower.html
{% extends "tools/base.html" %}

{% block content %}

<ul class="font lists">
    {% for tool in borrower_list %}
    <li>
        {{tool.owner}}
        {{tool.name}}
    </li>
    {% endfor %}

</ul>

{% endblock %}

tools/templates/tools/getstarted.html
{% load static %}
{% if not request.user.is_authenticated %}
<section class="d-flex justify-content-around font">

<div>
Join your Neighbors in borrowing freindly app
</div>
<a href="{% url 'accounts:signup' %}"">Get Started</a>
</section>
{% else %}

{% endif %}

tools/templates/tools/header.html
{% load static %}
<header>
    <h1 class=" title d-flex justify-content-center font">Hey Neighbor!</h1>
    <nav class="d-flex justify-content-around font nav-bar pb-4">
        <a href="{% url 'tools:mytools' %}">My Tools</a>
        <a href="{% url 'tools:neighbors' %}">Neighbors</a>
        <a href="{% url 'tools:borrower_feed' %}">Borrower's feed</a>
        {% if not request.user.is_authenticated %}
        <a href="{% url 'login' %}">Login</a>
        {% else %}
        <a href="{% url 'logout' %}">Logout</a>
        {% endif %}

    </nav>
</header>

tools/templates/tools/my_tool_update_form.html
{% extends "tools/base.html" %}

{% if request.user.is_authenticated %}
{% block content %}
<form class="font" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button>Submit</button>
</form>
{% endblock %}
{% endif %}

tools/templates/tools/my_tools.html
{% extends "tools/base.html" %}
{% if request.user.is_authenticated %}
{% block content %}
<section class="row no-gutters font justify-content-center">
    <a class="col-12 justify-content-center d-flex" href="{% url 'tools:newtool'%}">Add New Tool</a>
    <ul class="d-flex">
    {% for tool in tool_list %}
        <li class="d">
        <span class="tool-name">{{tool.name}}</span>
        <a href="{% url 'tools:update_tool' tool.id%}">Edit Tool</a>
        <a href="{% url 'tools:deletetool' tool.id %}">Delete</a>
        </li>
    {% endfor %}
    </ul>
</section>

{% endblock %}
{% endif %}

tools/templates/tools/neighbors.html
{% extends "tools/base.html" %}

{% block content %}

<ul class="font lists" >
    {% for neighbor in neighbors_list %}
    <li class="lists">
        <a href="{% url 'tools:users_tool' neighbor.pk %}">{{neighbor.username}}</a>
    </li>
    {% endfor %}

</ul>

{% endblock %}

tools/templates/tools/new_tool.html
{% extends "tools/start_page.html" %}

{% if request.user.is_authenticated %}
{% block content %}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button>Submit</button>
</form>
{% endblock %}
{% endif %}

tools/templates/tools/start_page.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body class="container">
        {% include "tools/header.html" %}
        {% include "tools/getstarted.html" %}
        {% block content %}
        {% endblock %}
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

tools/templates/tools/tool_confirm_delete.html
{% extends "tools/base.html" %}

{% if request.user.is_authenticated %}
{% block content %}
<form class="font" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}
{% endif %}

tools/templates/tools/users_tool.html
{% extends "tools/base.html" %}

{% block content %}

<ul class="font lists">
    {% for tool in users_tool_list %}
    <li>
        {{tool.owner}}
        {{tool.name}}
        {% if tool.is_available == True %}
        <button>Borrow Now</button>
        {% else %}
        <a> Not Available </a>
        {% endif %}
    </li>
    {% endfor %}

</ul>

{% endblock %}